BellaBeat Case Study
================
Dominic Igwebuike
2023-10-22

# Case Study of BellaBeats, A Fitness Brand That Serves Women.

## 1. INTRODUCTION

Bellabeat is a tech company that makes smart wearable gadgets.

They have a product catalogue of smart devices which function by
collecting key user-data including, activity, sleep, stress,
reproductive health, etc., to empower women with knowledge about their
daily habits and inform them on their health lifestyles.

This case study focuses on the analysis of the user data generated by
the fitness smart devices to see how it can help Bellabeat become
smarter in their marketing, messaging, and maximize growth opportunities
in the fitness industry.

This Case Study is completed as part of my Google Data Analytics
Professional Capstone projects and i will be working with the R
programming languge for this analysis.

The outcome of this analysis will help Bellabeat gain more insights on
how consumers use smart devices and apps and this will help Bellabeat
develop new on-demand features for their flagship Bellabeat App.

Bellabeat App is a consumer-centric app which provides users with health
lifestyle data that covers activity, sleep, stress, menstrual cycle, and
mindfullness habits. The Bellabeat App pulls and aggregate these data
from the wearable smart devices that their customers use.

## 2. BUSINESS TASK AND STAKEHOLDERS

My task is to uncover trends on how consumers use non-bellabeat smart
devices. The idea is to transfer these uncovered trends and insights to
similar Bellabeat products and use them to inform Bellabeats marketing
strategy.

**Stakeholders:**

Our stakeholders include:

1.  Urska Srsen

Ursen is Bellabeat cofounder and chief creative officer.

2.  Sando Mur

Sando is a cofounder of Bellabeat and a key member of Bellabeat
executive team

3.  Bellabeat Marketing Analytics

Team who would be directly using and implementing the insights generated
from this study.

## 3. ABOUT THE DATASET FOR THIS STUDY

We are using the publicly available Fitbit Fitness Tracker which is
gathered from Kaggle.com. Thanks to the Morbius team for putting it up.

## 4. DATA PROCESSING AND ANALYSIS

We are going to be using these list of R packages for our analysis.

- **tidyverse:** this includes dplyr for data wrangling, tidyr for
  tidying data, and ggplot2 for data visualization

- **janitor:** for data cleaning and tidying, contains functions for
  column name cleaning, duplicate rows removal, handling missing data,
  etc

- **lubridate:** for working with date and time data

- **skimr**: for summarizing data

- **ggrepel:** extends the capabilities of ggplot2 in making data points
  cleaner and removing overlaps

- **ggpubr:** extends the abilities of ggplot2 to create multiple plots,
  etc.

## INSTALLATION OF R PACKAGES

``` r
# code to make all my packages install properly

options(repos = "https://cran.r-project.org")
```

``` r
# we begin installation of the R packages

install.packages('tidyverse')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'tidyverse' successfully unpacked and MD5 sums checked
    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
install.packages('janitor')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'janitor' successfully unpacked and MD5 sums checked
    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
install.packages('lubridate')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'lubridate' successfully unpacked and MD5 sums checked

    ## Warning: cannot remove prior installation of package 'lubridate'

    ## Warning in file.copy(savedcopy, lib, recursive = TRUE): problem copying
    ## C:\Users\SHOW
    ## ICT\AppData\Local\R\win-library\4.3\00LOCK\lubridate\libs\x64\lubridate.dll to
    ## C:\Users\SHOW
    ## ICT\AppData\Local\R\win-library\4.3\lubridate\libs\x64\lubridate.dll:
    ## Permission denied

    ## Warning: restored 'lubridate'

    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
install.packages('skimr')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'skimr' successfully unpacked and MD5 sums checked
    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
install.packages('ggrepel')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'ggrepel' successfully unpacked and MD5 sums checked

    ## Warning: cannot remove prior installation of package 'ggrepel'

    ## Warning in file.copy(savedcopy, lib, recursive = TRUE): problem copying
    ## C:\Users\SHOW
    ## ICT\AppData\Local\R\win-library\4.3\00LOCK\ggrepel\libs\x64\ggrepel.dll to
    ## C:\Users\SHOW ICT\AppData\Local\R\win-library\4.3\ggrepel\libs\x64\ggrepel.dll:
    ## Permission denied

    ## Warning: restored 'ggrepel'

    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
install.packages('ggpubr')
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'ggpubr' successfully unpacked and MD5 sums checked
    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

Now that all the packages are installed, we get them ready for our
analysis.

``` r
# importing the libraries

library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(lubridate)
library(skimr)
library(ggrepel)
library(ggpubr)
```

## DATASETS IMPORTATION

We import the datasets already downloaded from Kaggle.

There are 18 CSV files in the Fitbit Fitness Tracker data, capturing
daily down to hours and seconds of activities on the app, however we
will not be using all the datasets for this analysis.

We will focus on the most relevant datasets for our analysis, and they
include:

- Daily activity data

- Daily sleep data

- Hourly steps.

``` r
# importing the data files

daily_activity <- read_csv('dailyActivity_merged.csv', show_col_types = FALSE)

daily_sleep <- read_csv('sleepDay_merged.csv', show_col_types = FALSE)

hourly_steps <-read_csv('hourlySteps_merged.csv', show_col_types = FALSE)
```

Let’s take a closer look at the datasets

``` r
# let's look at the top view of the daily activity dataset

head(daily_activity)
```

    ## # A tibble: 6 × 15
    ##           Id ActivityDate TotalSteps TotalDistance TrackerDistance
    ##        <dbl> <chr>             <dbl>         <dbl>           <dbl>
    ## 1 1503960366 4/12/2016         13162          8.5             8.5 
    ## 2 1503960366 4/13/2016         10735          6.97            6.97
    ## 3 1503960366 4/14/2016         10460          6.74            6.74
    ## 4 1503960366 4/15/2016          9762          6.28            6.28
    ## 5 1503960366 4/16/2016         12669          8.16            8.16
    ## 6 1503960366 4/17/2016          9705          6.48            6.48
    ## # ℹ 10 more variables: LoggedActivitiesDistance <dbl>,
    ## #   VeryActiveDistance <dbl>, ModeratelyActiveDistance <dbl>,
    ## #   LightActiveDistance <dbl>, SedentaryActiveDistance <dbl>,
    ## #   VeryActiveMinutes <dbl>, FairlyActiveMinutes <dbl>,
    ## #   LightlyActiveMinutes <dbl>, SedentaryMinutes <dbl>, Calories <dbl>

``` r
# Checking the structure of the daily_activity dataframe

str(daily_activity)
```

    ## spc_tbl_ [940 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id                      : num [1:940] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDate            : chr [1:940] "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ TotalSteps              : num [1:940] 13162 10735 10460 9762 12669 ...
    ##  $ TotalDistance           : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ TrackerDistance         : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ LoggedActivitiesDistance: num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveDistance      : num [1:940] 1.88 1.57 2.44 2.14 2.71 ...
    ##  $ ModeratelyActiveDistance: num [1:940] 0.55 0.69 0.4 1.26 0.41 ...
    ##  $ LightActiveDistance     : num [1:940] 6.06 4.71 3.91 2.83 5.04 ...
    ##  $ SedentaryActiveDistance : num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveMinutes       : num [1:940] 25 21 30 29 36 38 42 50 28 19 ...
    ##  $ FairlyActiveMinutes     : num [1:940] 13 19 11 34 10 20 16 31 12 8 ...
    ##  $ LightlyActiveMinutes    : num [1:940] 328 217 181 209 221 164 233 264 205 211 ...
    ##  $ SedentaryMinutes        : num [1:940] 728 776 1218 726 773 ...
    ##  $ Calories                : num [1:940] 1985 1797 1776 1745 1863 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityDate = col_character(),
    ##   ..   TotalSteps = col_double(),
    ##   ..   TotalDistance = col_double(),
    ##   ..   TrackerDistance = col_double(),
    ##   ..   LoggedActivitiesDistance = col_double(),
    ##   ..   VeryActiveDistance = col_double(),
    ##   ..   ModeratelyActiveDistance = col_double(),
    ##   ..   LightActiveDistance = col_double(),
    ##   ..   SedentaryActiveDistance = col_double(),
    ##   ..   VeryActiveMinutes = col_double(),
    ##   ..   FairlyActiveMinutes = col_double(),
    ##   ..   LightlyActiveMinutes = col_double(),
    ##   ..   SedentaryMinutes = col_double(),
    ##   ..   Calories = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

There are 940 rows of data and 15 columns in the daily_activity dataset.

We notice that all the data are of type numerical including the id
column, however, the ActivityDate column is character type, we will be
changing this to date type later.

``` r
# inspecting the hourly_steps data

head(hourly_steps)
```

    ## # A tibble: 6 × 3
    ##           Id ActivityHour          StepTotal
    ##        <dbl> <chr>                     <dbl>
    ## 1 1503960366 4/12/2016 12:00:00 AM       373
    ## 2 1503960366 4/12/2016 1:00:00 AM        160
    ## 3 1503960366 4/12/2016 2:00:00 AM        151
    ## 4 1503960366 4/12/2016 3:00:00 AM          0
    ## 5 1503960366 4/12/2016 4:00:00 AM          0
    ## 6 1503960366 4/12/2016 5:00:00 AM          0

``` r
str(hourly_steps)
```

    ## spc_tbl_ [22,099 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id          : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityHour: chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
    ##  $ StepTotal   : num [1:22099] 373 160 151 0 0 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityHour = col_character(),
    ##   ..   StepTotal = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
# inspecting daily sleep activity

head(daily_sleep)
```

    ## # A tibble: 6 × 5
    ##           Id SleepDay        TotalSleepRecords TotalMinutesAsleep TotalTimeInBed
    ##        <dbl> <chr>                       <dbl>              <dbl>          <dbl>
    ## 1 1503960366 4/12/2016 12:0…                 1                327            346
    ## 2 1503960366 4/13/2016 12:0…                 2                384            407
    ## 3 1503960366 4/15/2016 12:0…                 1                412            442
    ## 4 1503960366 4/16/2016 12:0…                 2                340            367
    ## 5 1503960366 4/17/2016 12:0…                 1                700            712
    ## 6 1503960366 4/19/2016 12:0…                 1                304            320

``` r
str(daily_sleep)
```

    ## spc_tbl_ [413 × 5] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id                : num [1:413] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ SleepDay          : chr [1:413] "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
    ##  $ TotalSleepRecords : num [1:413] 1 2 1 2 1 1 1 1 1 1 ...
    ##  $ TotalMinutesAsleep: num [1:413] 327 384 412 340 700 304 360 325 361 430 ...
    ##  $ TotalTimeInBed    : num [1:413] 346 407 442 367 712 320 377 364 384 449 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   SleepDay = col_character(),
    ##   ..   TotalSleepRecords = col_double(),
    ##   ..   TotalMinutesAsleep = col_double(),
    ##   ..   TotalTimeInBed = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

We can notice that in all the datasets, the date columns are of
character type which needs to be converted to date type.

Let’s investigate other aspects of the data and then clean it.

Now we want to have an idea of the number of unique users of the fitbit
app, this will help us deal with duplicate values that can affect our
analysis.

``` r
# how many unique user are in the datasets?

n_unique(daily_activity$Id)
```

    ## [1] 33

``` r
n_unique(hourly_steps$Id)
```

    ## [1] 33

``` r
n_unique(daily_sleep$Id)
```

    ## [1] 24

We can see that there are 33 unique users for the daily activity and
hourly steps while there are only 24 users of the daily sleep feature of
the application.

### Dealing With Duplicates

Now, let’s look for duplicates in the dataset and remove them.

``` r
# looking for duplicate data in the daily_activity dataset

sum(duplicated(daily_activity))
```

    ## [1] 0

``` r
# duplicates in hourly_steps

sum(duplicated(hourly_steps))
```

    ## [1] 0

``` r
# duplicates in daily_sleep

sum(duplicated(daily_sleep))
```

    ## [1] 3

There are no duplicates in the daily_activity and hourly_steps data
while for the daily_sleep, there are 3 duplicates.

We will remove these duplicates

``` r
# how many rows are in the daily_sleep dataset?

nrow(daily_sleep)
```

    ## [1] 413

There are 413 rows of data in the daily_sleep dataset, and 3 out of
these are duplicates, now let’s remove the duplicates

## REMOVE DUPLICATES AND NAs

``` r
daily_sleep <- daily_sleep %>% 
  distinct() %>%
  drop_na()
```

Now let’s check the number of rows again

``` r
nrow(daily_sleep)
```

    ## [1] 410

Now we have 410 rows after the removal of the duplicate rows.

Let’s confirm that the duplicates have actually been removed by checking
for duplicates again.

``` r
sum(duplicated(daily_sleep))
```

    ## [1] 0

Duplicates have been removed from the daily_sleep data.

Now let’s remove empty rows and null values from the other datasets.

``` r
nrow(daily_activity)
```

    ## [1] 940

``` r
nrow(hourly_steps)
```

    ## [1] 22099

There are 940 row of data in the daily_activity dataset and 22099 rows
for the hourly_steps which captures hourly data.

Let’s remove N/As and see how much data we will have.

``` r
daily_activity <- daily_activity %>% 
  drop_na()
nrow(daily_activity)
```

    ## [1] 940

There are no empty rows in daily_activity

``` r
hourly_steps <- hourly_steps %>% 
  drop_na()
nrow(hourly_steps)
```

    ## [1] 22099

Also there are no null values in the hourly_steps data.

### Standardizing The Column Names

We want the datasets to have the same format in the naming of their
columns so that we can easily merge them later, so we will clean and
format the datasets where necessary to meet the specifications.

``` r
daily_activity <- daily_activity %>% 
  clean_names()
head(daily_activity)
```

    ## # A tibble: 6 × 15
    ##           id activity_date total_steps total_distance tracker_distance
    ##        <dbl> <chr>               <dbl>          <dbl>            <dbl>
    ## 1 1503960366 4/12/2016           13162           8.5              8.5 
    ## 2 1503960366 4/13/2016           10735           6.97             6.97
    ## 3 1503960366 4/14/2016           10460           6.74             6.74
    ## 4 1503960366 4/15/2016            9762           6.28             6.28
    ## 5 1503960366 4/16/2016           12669           8.16             8.16
    ## 6 1503960366 4/17/2016            9705           6.48             6.48
    ## # ℹ 10 more variables: logged_activities_distance <dbl>,
    ## #   very_active_distance <dbl>, moderately_active_distance <dbl>,
    ## #   light_active_distance <dbl>, sedentary_active_distance <dbl>,
    ## #   very_active_minutes <dbl>, fairly_active_minutes <dbl>,
    ## #   lightly_active_minutes <dbl>, sedentary_minutes <dbl>, calories <dbl>

``` r
head(daily_sleep)
```

    ## # A tibble: 6 × 5
    ##           Id SleepDay        TotalSleepRecords TotalMinutesAsleep TotalTimeInBed
    ##        <dbl> <chr>                       <dbl>              <dbl>          <dbl>
    ## 1 1503960366 4/12/2016 12:0…                 1                327            346
    ## 2 1503960366 4/13/2016 12:0…                 2                384            407
    ## 3 1503960366 4/15/2016 12:0…                 1                412            442
    ## 4 1503960366 4/16/2016 12:0…                 2                340            367
    ## 5 1503960366 4/17/2016 12:0…                 1                700            712
    ## 6 1503960366 4/19/2016 12:0…                 1                304            320

We are going to format the columns of daily_sleep to lower case for
uniformity.

``` r
# we use the clean_names function from the janitor package to do this

daily_sleep <- daily_sleep %>% 
  clean_names()

head(daily_sleep)
```

    ## # A tibble: 6 × 5
    ##          id sleep_day total_sleep_records total_minutes_asleep total_time_in_bed
    ##       <dbl> <chr>                   <dbl>                <dbl>             <dbl>
    ## 1    1.50e9 4/12/201…                   1                  327               346
    ## 2    1.50e9 4/13/201…                   2                  384               407
    ## 3    1.50e9 4/15/201…                   1                  412               442
    ## 4    1.50e9 4/16/201…                   2                  340               367
    ## 5    1.50e9 4/17/201…                   1                  700               712
    ## 6    1.50e9 4/19/201…                   1                  304               320

And same for the hourly_steps data for consistency

``` r
head(hourly_steps)
```

    ## # A tibble: 6 × 3
    ##           Id ActivityHour          StepTotal
    ##        <dbl> <chr>                     <dbl>
    ## 1 1503960366 4/12/2016 12:00:00 AM       373
    ## 2 1503960366 4/12/2016 1:00:00 AM        160
    ## 3 1503960366 4/12/2016 2:00:00 AM        151
    ## 4 1503960366 4/12/2016 3:00:00 AM          0
    ## 5 1503960366 4/12/2016 4:00:00 AM          0
    ## 6 1503960366 4/12/2016 5:00:00 AM          0

``` r
hourly_steps <- hourly_steps %>% 
  clean_names()
head(hourly_steps)
```

    ## # A tibble: 6 × 3
    ##           id activity_hour         step_total
    ##        <dbl> <chr>                      <dbl>
    ## 1 1503960366 4/12/2016 12:00:00 AM        373
    ## 2 1503960366 4/12/2016 1:00:00 AM         160
    ## 3 1503960366 4/12/2016 2:00:00 AM         151
    ## 4 1503960366 4/12/2016 3:00:00 AM           0
    ## 5 1503960366 4/12/2016 4:00:00 AM           0
    ## 6 1503960366 4/12/2016 5:00:00 AM           0

### Formatting and Renaming the Date Columns

Now we are going to format the date columns of the datasets from
character type to the right date type format and then rename the
daily_activity and daily_sleep date columns as we will merge them later
for analysis.

``` r
# Formatting the daily-activity date column

daily_activity <- daily_activity %>% 
  rename(date = activity_date) %>% 
  mutate(date = as_date(date, format = "%m/%d/%Y"))
```

``` r
str(daily_activity)
```

    ## tibble [940 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ id                        : num [1:940] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ date                      : Date[1:940], format: "2016-04-12" "2016-04-13" ...
    ##  $ total_steps               : num [1:940] 13162 10735 10460 9762 12669 ...
    ##  $ total_distance            : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ tracker_distance          : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ logged_activities_distance: num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ very_active_distance      : num [1:940] 1.88 1.57 2.44 2.14 2.71 ...
    ##  $ moderately_active_distance: num [1:940] 0.55 0.69 0.4 1.26 0.41 ...
    ##  $ light_active_distance     : num [1:940] 6.06 4.71 3.91 2.83 5.04 ...
    ##  $ sedentary_active_distance : num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ very_active_minutes       : num [1:940] 25 21 30 29 36 38 42 50 28 19 ...
    ##  $ fairly_active_minutes     : num [1:940] 13 19 11 34 10 20 16 31 12 8 ...
    ##  $ lightly_active_minutes    : num [1:940] 328 217 181 209 221 164 233 264 205 211 ...
    ##  $ sedentary_minutes         : num [1:940] 728 776 1218 726 773 ...
    ##  $ calories                  : num [1:940] 1985 1797 1776 1745 1863 ...

We will do same for the daily_sleep sleep_day column, note that the
sleep_day column also contains time element which needs to be converted
in the right format for this conversion to work.

We will be removing the time aspect because we don’t need it for this
analysis, this is why we are using as_date() instead of as_datetime()
function.

I will assign the changes to a new variable daily_sleep1 so that if we
encounter an error in the code it will not affect the main daily_sleep
dataframe.

``` r
daily_sleep1 <- daily_sleep %>% 
  rename(date = sleep_day) %>% 
  mutate(date = as_date(date, format = "%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `date = as_date(date, format = "%m/%d/%Y %I:%M:%S %p", tz =
    ##   Sys.timezone())`.
    ## Caused by warning:
    ## ! `tz` argument is ignored by `as_date()`

``` r
daily_sleep1
```

    ## # A tibble: 410 × 5
    ##         id date       total_sleep_records total_minutes_asleep total_time_in_bed
    ##      <dbl> <date>                   <dbl>                <dbl>             <dbl>
    ##  1  1.50e9 2016-04-12                   1                  327               346
    ##  2  1.50e9 2016-04-13                   2                  384               407
    ##  3  1.50e9 2016-04-15                   1                  412               442
    ##  4  1.50e9 2016-04-16                   2                  340               367
    ##  5  1.50e9 2016-04-17                   1                  700               712
    ##  6  1.50e9 2016-04-19                   1                  304               320
    ##  7  1.50e9 2016-04-20                   1                  360               377
    ##  8  1.50e9 2016-04-21                   1                  325               364
    ##  9  1.50e9 2016-04-23                   1                  361               384
    ## 10  1.50e9 2016-04-24                   1                  430               449
    ## # ℹ 400 more rows

``` r
head(daily_activity)
```

    ## # A tibble: 6 × 15
    ##           id date       total_steps total_distance tracker_distance
    ##        <dbl> <date>           <dbl>          <dbl>            <dbl>
    ## 1 1503960366 2016-04-12       13162           8.5              8.5 
    ## 2 1503960366 2016-04-13       10735           6.97             6.97
    ## 3 1503960366 2016-04-14       10460           6.74             6.74
    ## 4 1503960366 2016-04-15        9762           6.28             6.28
    ## 5 1503960366 2016-04-16       12669           8.16             8.16
    ## 6 1503960366 2016-04-17        9705           6.48             6.48
    ## # ℹ 10 more variables: logged_activities_distance <dbl>,
    ## #   very_active_distance <dbl>, moderately_active_distance <dbl>,
    ## #   light_active_distance <dbl>, sedentary_active_distance <dbl>,
    ## #   very_active_minutes <dbl>, fairly_active_minutes <dbl>,
    ## #   lightly_active_minutes <dbl>, sedentary_minutes <dbl>, calories <dbl>

``` r
head(daily_sleep1)
```

    ## # A tibble: 6 × 5
    ##         id date       total_sleep_records total_minutes_asleep total_time_in_bed
    ##      <dbl> <date>                   <dbl>                <dbl>             <dbl>
    ## 1   1.50e9 2016-04-12                   1                  327               346
    ## 2   1.50e9 2016-04-13                   2                  384               407
    ## 3   1.50e9 2016-04-15                   1                  412               442
    ## 4   1.50e9 2016-04-16                   2                  340               367
    ## 5   1.50e9 2016-04-17                   1                  700               712
    ## 6   1.50e9 2016-04-19                   1                  304               320

Everything worked out fine so, we will proceed to formatting the
hourly_steps columns.

``` r
head(hourly_steps)
```

    ## # A tibble: 6 × 3
    ##           id activity_hour         step_total
    ##        <dbl> <chr>                      <dbl>
    ## 1 1503960366 4/12/2016 12:00:00 AM        373
    ## 2 1503960366 4/12/2016 1:00:00 AM         160
    ## 3 1503960366 4/12/2016 2:00:00 AM         151
    ## 4 1503960366 4/12/2016 3:00:00 AM           0
    ## 5 1503960366 4/12/2016 4:00:00 AM           0
    ## 6 1503960366 4/12/2016 5:00:00 AM           0

``` r
hourly_steps2 <- hourly_steps %>% 
  rename(date_time = activity_hour) %>% 
  mutate(date_time = as.POSIXct(date_time, format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))
```

``` r
# looking at the first 5 rows of the dataframe
head(hourly_steps2)
```

    ## # A tibble: 6 × 3
    ##           id date_time           step_total
    ##        <dbl> <dttm>                   <dbl>
    ## 1 1503960366 2016-04-12 00:00:00        373
    ## 2 1503960366 2016-04-12 01:00:00        160
    ## 3 1503960366 2016-04-12 02:00:00        151
    ## 4 1503960366 2016-04-12 03:00:00          0
    ## 5 1503960366 2016-04-12 04:00:00          0
    ## 6 1503960366 2016-04-12 05:00:00          0

Everything worked fine with the renaming of the activity_hour column
from character to POSIXct data type, and renaming to date_time, so let’s
reassign to hourly_steps.

``` r
hourly_steps <- hourly_steps2
```

We do the same for daily_sleep

``` r
daily_sleep <- daily_sleep1
```

Checking the reassignments

``` r
head(daily_sleep)
```

    ## # A tibble: 6 × 5
    ##         id date       total_sleep_records total_minutes_asleep total_time_in_bed
    ##      <dbl> <date>                   <dbl>                <dbl>             <dbl>
    ## 1   1.50e9 2016-04-12                   1                  327               346
    ## 2   1.50e9 2016-04-13                   2                  384               407
    ## 3   1.50e9 2016-04-15                   1                  412               442
    ## 4   1.50e9 2016-04-16                   2                  340               367
    ## 5   1.50e9 2016-04-17                   1                  700               712
    ## 6   1.50e9 2016-04-19                   1                  304               320

``` r
head(hourly_steps)
```

    ## # A tibble: 6 × 3
    ##           id date_time           step_total
    ##        <dbl> <dttm>                   <dbl>
    ## 1 1503960366 2016-04-12 00:00:00        373
    ## 2 1503960366 2016-04-12 01:00:00        160
    ## 3 1503960366 2016-04-12 02:00:00        151
    ## 4 1503960366 2016-04-12 03:00:00          0
    ## 5 1503960366 2016-04-12 04:00:00          0
    ## 6 1503960366 2016-04-12 05:00:00          0

Now that we have the datasets clean as we need it to be, let’s merge the
daily_activity and daily-sleep datasets together using the id and date
columns.

``` r
daily_activity_n_sleep <- merge(daily_activity, daily_sleep, by = c("id", "date"))
```

Let’s take a look at the merged data

``` r
head(daily_activity_n_sleep)
```

    ##           id       date total_steps total_distance tracker_distance
    ## 1 1503960366 2016-04-12       13162           8.50             8.50
    ## 2 1503960366 2016-04-13       10735           6.97             6.97
    ## 3 1503960366 2016-04-15        9762           6.28             6.28
    ## 4 1503960366 2016-04-16       12669           8.16             8.16
    ## 5 1503960366 2016-04-17        9705           6.48             6.48
    ## 6 1503960366 2016-04-19       15506           9.88             9.88
    ##   logged_activities_distance very_active_distance moderately_active_distance
    ## 1                          0                 1.88                       0.55
    ## 2                          0                 1.57                       0.69
    ## 3                          0                 2.14                       1.26
    ## 4                          0                 2.71                       0.41
    ## 5                          0                 3.19                       0.78
    ## 6                          0                 3.53                       1.32
    ##   light_active_distance sedentary_active_distance very_active_minutes
    ## 1                  6.06                         0                  25
    ## 2                  4.71                         0                  21
    ## 3                  2.83                         0                  29
    ## 4                  5.04                         0                  36
    ## 5                  2.51                         0                  38
    ## 6                  5.03                         0                  50
    ##   fairly_active_minutes lightly_active_minutes sedentary_minutes calories
    ## 1                    13                    328               728     1985
    ## 2                    19                    217               776     1797
    ## 3                    34                    209               726     1745
    ## 4                    10                    221               773     1863
    ## 5                    20                    164               539     1728
    ## 6                    31                    264               775     2035
    ##   total_sleep_records total_minutes_asleep total_time_in_bed
    ## 1                   1                  327               346
    ## 2                   2                  384               407
    ## 3                   1                  412               442
    ## 4                   2                  340               367
    ## 5                   1                  700               712
    ## 6                   1                  304               320

## DATA ANALYSIS

Now, we are going to analyze the data and begin to uncover insights
which we hope will help the marketing team at Bellabeats take their game
to a new level.

In order to try and uncover hidden trends and user behaviours of our
smart device users, we need to ask some questions like.

1.  What categories of users do we have based on the data available to
    us?
2.  How many steps do our users take weekly?
3.  How many hours do they sleep?
4.  Which days are they most active?
5.  How frequently do they use their smart devices?
6.  Are their relationships between activities like hours of sleep vs
    calories or number of steps versus calories burned?
7.  How long do they use their smart devices per day?

Answering these questions will help us gain insights into how smart
device users behave and the key features of the devices they appreciate
the most.

These insights will then inform on app designs, marketing style and
messaging, app features development and much more, which overall will
deliver value to users and help grow the business for Bellabeat.

So, right away lets find out our answers:

### Categories of Users

``` r
# We will have a look at our data to see all the variables available which will help us find our answer.

view(daily_activity_n_sleep)
```

``` r
colnames(daily_activity_n_sleep)
```

    ##  [1] "id"                         "date"                      
    ##  [3] "total_steps"                "total_distance"            
    ##  [5] "tracker_distance"           "logged_activities_distance"
    ##  [7] "very_active_distance"       "moderately_active_distance"
    ##  [9] "light_active_distance"      "sedentary_active_distance" 
    ## [11] "very_active_minutes"        "fairly_active_minutes"     
    ## [13] "lightly_active_minutes"     "sedentary_minutes"         
    ## [15] "calories"                   "total_sleep_records"       
    ## [17] "total_minutes_asleep"       "total_time_in_bed"

Based on the column names, we cannot specifically identify the
categories, however, we can group users based on the active distance
they covered using the app.

We have the data starting from the very active distance to sedentary
distance.

According to the 10000 step protocol, walking activities can be groups
based on the number of steps walked into the following:

- **Sedentary:** Less than 5,000 steps daily

- **Low active:** About 5,000 to 7,499 steps daily

- **Moderately active:** About 7,500 to 9,999 steps daily

- **Active:** More than 10,000 steps daily

- **Highly active:** More than 12,500 steps daily

This information is obtainable here, *“How Many Steps a Day Is
Considered Active? (medicinenet.com)”*

So we will group app users based on this guideline

``` r
# Let's calculate the average step of all users daily.

daily_average <- daily_activity_n_sleep %>% 
  group_by(id) %>% 
    summarise(average_steps_per_day = mean(total_steps),
    average_calories_burned_per_day = mean(calories), 
    average_sleep_per_day = mean(total_minutes_asleep)
    )

head(daily_average, 10)
```

    ## # A tibble: 10 × 4
    ##            id average_steps_per_day average_calories_bur…¹ average_sleep_per_day
    ##         <dbl>                 <dbl>                  <dbl>                 <dbl>
    ##  1 1503960366                12406.                  1872.                  360.
    ##  2 1644430081                 7968.                  2978.                  294 
    ##  3 1844505072                 3477                   1676.                  652 
    ##  4 1927972279                 1490                   2316.                  417 
    ##  5 2026352035                 5619.                  1541.                  506.
    ##  6 2320127002                 5079                   1804                    61 
    ##  7 2347167796                 8533.                  1971.                  447.
    ##  8 3977333714                11218                   1560.                  294.
    ##  9 4020332650                 6597.                  3195                   349.
    ## 10 4319703577                 7125.                  2025.                  477.
    ## # ℹ abbreviated name: ¹​average_calories_burned_per_day

Now that we have the average steps by each user, let’s classify the user
category based on the 10000 steps protocol.

``` r
user_category <- daily_average %>% 
  mutate(user_category = case_when(
    average_steps_per_day < 5000 ~"sedentary",
    average_steps_per_day >= 5000 & average_steps_per_day < 7499 ~"low active",
    average_steps_per_day >= 7500 & average_steps_per_day < 9999 ~ "moderately active",
    average_steps_per_day >=10000 & average_steps_per_day < 12499 ~"active",
    average_steps_per_day >= 12500 ~"highly active"))

head(user_category)
```

    ## # A tibble: 6 × 5
    ##           id average_steps_per_day average_calories_burn…¹ average_sleep_per_day
    ##        <dbl>                 <dbl>                   <dbl>                 <dbl>
    ## 1 1503960366                12406.                   1872.                  360.
    ## 2 1644430081                 7968.                   2978.                  294 
    ## 3 1844505072                 3477                    1676.                  652 
    ## 4 1927972279                 1490                    2316.                  417 
    ## 5 2026352035                 5619.                   1541.                  506.
    ## 6 2320127002                 5079                    1804                    61 
    ## # ℹ abbreviated name: ¹​average_calories_burned_per_day
    ## # ℹ 1 more variable: user_category <chr>

``` r
# to see the whole dataframe as a table and get more understanding of it.
  view(user_category)
```

Let’s find the percentage of users in the categories and then visualize
it using pie chart.

``` r
user_type_percentage <- user_category %>% 
  group_by(user_category) %>% 
  summarise(user_count= n()) %>% 
  mutate(user_count_total = sum(user_count)) %>%  
  group_by(user_category) %>% 
  summarise(user_percent = user_count/user_count_total) %>% 
  mutate(labels = scales::percent(user_percent))
  
head(user_type_percentage)
```

    ## # A tibble: 5 × 3
    ##   user_category     user_percent labels
    ##   <chr>                    <dbl> <chr> 
    ## 1 active                  0.167  16.7% 
    ## 2 highly active           0.0417 4.2%  
    ## 3 low active              0.208  20.8% 
    ## 4 moderately active       0.375  37.5% 
    ## 5 sedentary               0.208  20.8%

Visualization of User Categories

``` r
user_type_percentage %>% 
  ggplot(aes(x="", y=user_percent, fill=user_category))+
  geom_bar(stat="identity", width=1)+
  coord_polar("y", start=0)+
  theme_light()+
  theme( axis.title.x = element_blank(),
         axis.title.y= element_blank(),
         panel.border = element_blank(),
         panel.grid = element_blank(),
         axis.ticks = element_blank(),
         axis.text.x = element_blank(),
         plot.title = element_text(hjust = 0.5, size=10, face="bold"))+
  scale_fill_brewer(palette = "YlOrBr")+
  geom_text(aes(label= labels),position = position_stack(vjust = 0.5))+
  labs(title= "Categories of Users Based on Activity")
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/categories%20by%20activity.png?raw=true)<!-- -->

We can see that 38% of users are moderately active, there is a fair
share of users who are sedentary and low-active about 21% each. 17
percent of users are very active, while only 4% are highly active users.

With this knowledge, the dev team at Bellabeat should see the importance
of developing key notification features in their app and smart devices
that will boost the activity levels of users. This way they will be able
to convert more than 40% of smart device users from low and sedentary to
active users.

The marketing team should design reward programs that can be built into
the overall design of the smart devices to encourage and reward users.
Perhaps competitions and leader boards would be a good idea.

### Weekday Activity Analysis

We want to analyze the activities of users and compare them by week
days, this will give us insights into how the users perform on a day to
day basis.

We will analyze both the activities (steps walked) and sleep habits of
users on a day to day basis to uncover trends.

``` r
# extract weekdays from the date column and create a new column for it

weekday_steps_n_sleep <- daily_activity_n_sleep %>%
  mutate(weekday = weekdays.Date(date))

# order the weekdays in the right calendar weekday sequence
weekday_steps_n_sleep$weekday <- ordered(weekday_steps_n_sleep$weekday, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

# let's calculate the daily steps and sleep time and group them by weekdays.

weekday_steps_n_sleep <- weekday_steps_n_sleep %>% 
  group_by(weekday) %>% 
  summarise(avg_steps_per_day = mean(total_steps), avg_sleep_per_day = mean(total_minutes_asleep))

head(weekday_steps_n_sleep,7)
```

    ## # A tibble: 7 × 3
    ##   weekday   avg_steps_per_day avg_sleep_per_day
    ##   <ord>                 <dbl>             <dbl>
    ## 1 Monday                9273.              420.
    ## 2 Tuesday               9183.              405.
    ## 3 Wednesday             8023.              435.
    ## 4 Thursday              8184.              401.
    ## 5 Friday                7901.              405.
    ## 6 Saturday              9871.              419.
    ## 7 Sunday                7298.              453.

Let’s visualize this to see if we can pick out any trends.

``` r
weekday_steps_n_sleep %>% 
ggplot(aes(x = weekday, y= avg_steps_per_day))+
  geom_col(inherit.aes = TRUE, fill= "brown")+
  geom_hline(yintercept= 7500 )+
  labs(title= "Average Steps Per Weekday", x= "", y="")+
  theme(axis.text.x = element_text(angle=45, vjust = 0.5, hjust= 1))
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/steps%20per%20weekday.png?raw=true)<!-- -->

We can see that all users walk more than 7500 steps per day all the days
of the week except Sundays which is commendable, it can be assumed that
users perhaps stay indoors much more on Sundays compared to other days
of the week which may be the cause of the fewer steps on Sundays.

We can also see that users are most active on Saturdays, and this
understandable as Saturdays are when people get more involved in fitness
activities.

``` r
weekday_steps_n_sleep %>% 
ggplot(aes(x = weekday, y= avg_sleep_per_day))+
  geom_col(inherit.aes = TRUE, fill= "orange")+
  geom_hline(yintercept= 480 )+
  labs(title= "Average Sleep Per Weekday", x= "", y="")+
  theme(axis.text.x = element_text(angle=45, vjust = 0.5, hjust= 1))
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/sleep%20per%20weekday.png?raw=true)<!-- -->

We can see that users get about 400 minutes (6 and a half hours) of
sleep everyday of the week and slightly higher on Sundays, however this
falls short of the recommended 8 hours sleep per day.

Another trend we’d like to uncover is the daily usage pattern. We want
to know which times of the day that users are most active and clock-in
high activities and which times of the day when they are less active.

We will use the hourly_steps data for this.

### Hourly Steps Throughout The Day

``` r
hourly_steps_modified <- hourly_steps %>% 
  separate(date_time, into = c("date", "time"), sep= " ") %>% 
  mutate(
    date = ymd(date),
    time = if_else(time =="00:00:00", "00:00:00", time)
  )
```

    ## Warning: Expected 2 pieces. Missing pieces filled with `NA` in 934 rows [1, 25, 49, 73,
    ## 97, 121, 145, 169, 193, 217, 241, 265, 289, 313, 337, 361, 385, 409, 433, 457,
    ## ...].

I tried separating the date_time column into its separate components so
we can use the time column for our analysis, however, the rows with time
equal to 00:00:00 (midnight) values are giving NA values, therefore we
need to replace the NA values with the same 00:00:00 values.

I tried correcting this with if_else function but it did not work.

So, let’s replace them

``` r
hourly_steps_modified <- hourly_steps_modified %>% 
  mutate(
    time = replace_na(time, "00:00:00")
  )

head(hourly_steps_modified)
```

    ## # A tibble: 6 × 4
    ##           id date       time     step_total
    ##        <dbl> <date>     <chr>         <dbl>
    ## 1 1503960366 2016-04-12 00:00:00        373
    ## 2 1503960366 2016-04-12 01:00:00        160
    ## 3 1503960366 2016-04-12 02:00:00        151
    ## 4 1503960366 2016-04-12 03:00:00          0
    ## 5 1503960366 2016-04-12 04:00:00          0
    ## 6 1503960366 2016-04-12 05:00:00          0

Now, we have modified the hourly_steps data, let’s find the average
steps by hours and then visualize…

``` r
hourly_steps_modified %>% 
  group_by(time) %>% 
  summarize(average_hourly_steps = round(mean(step_total),2))
```

    ## # A tibble: 24 × 2
    ##    time     average_hourly_steps
    ##    <chr>                   <dbl>
    ##  1 00:00:00                42.2 
    ##  2 01:00:00                23.1 
    ##  3 02:00:00                17.1 
    ##  4 03:00:00                 6.43
    ##  5 04:00:00                12.7 
    ##  6 05:00:00                43.9 
    ##  7 06:00:00               179.  
    ##  8 07:00:00               306.  
    ##  9 08:00:00               428.  
    ## 10 09:00:00               433.  
    ## # ℹ 14 more rows

``` r
# visualizing the data

 hourly_steps_modified %>% 
  group_by(time) %>% 
  summarize(average_hourly_steps = mean(step_total)) %>% 
  ggplot()+
  geom_col(mapping=aes(x = time, y= average_hourly_steps, fill = average_hourly_steps))+
  labs(title= "Average Hourly Steps Per Day", x= "", y="")+
  scale_fill_gradient(low="brown", high="orange")+
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust= 1))
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/hourly%20steps.png?raw=true)<!-- -->

As we can see from the charts, users are most active between 8:00AM and
19:00PM, with peak active periods between 12:00PM - 14:00PM and
16:00PM - 19:00PM.

### Use of Smart Device

So far, we have explored user activities as it relates to time patterns,
weekday patterns and user categories based on activity levels, now we
want to explore usage frequency to understand the behavior around the
use of smart devices.

We want to understand how often, our users use their devices. We are
going to group users into categories based on their usage frequency.
This can help the marketing team make informed decision when planning on
market segmentation in their marketing campaigns.

We will categorize smart device users into 3:

1.  Those who use their devices between 21 to 31 days - high use
2.  Those who use their devices between 10 to 20 days - moderate use
3.  Those who use their devices between 1 to 10 days - low use

``` r
daily_use <- daily_activity_n_sleep %>% 
  group_by(id) %>% 
  summarise(sum_of_days_used = sum(n()) )
head(daily_use)
```

    ## # A tibble: 6 × 2
    ##           id sum_of_days_used
    ##        <dbl>            <int>
    ## 1 1503960366               25
    ## 2 1644430081                4
    ## 3 1844505072                3
    ## 4 1927972279                5
    ## 5 2026352035               28
    ## 6 2320127002                1

Let’s create our categories.

``` r
daily_use <- daily_use %>% 
 mutate(usage = case_when(
     sum_of_days_used >= 21 & sum_of_days_used <=31 ~ "high use",
     sum_of_days_used >= 10 & sum_of_days_used <=20 ~ "moderate use",
     sum_of_days_used >= 1 & sum_of_days_used <=9 ~ "low use"
   )
 )
daily_use
```

    ## # A tibble: 24 × 3
    ##            id sum_of_days_used usage       
    ##         <dbl>            <int> <chr>       
    ##  1 1503960366               25 high use    
    ##  2 1644430081                4 low use     
    ##  3 1844505072                3 low use     
    ##  4 1927972279                5 low use     
    ##  5 2026352035               28 high use    
    ##  6 2320127002                1 low use     
    ##  7 2347167796               15 moderate use
    ##  8 3977333714               28 high use    
    ##  9 4020332650                8 low use     
    ## 10 4319703577               26 high use    
    ## # ℹ 14 more rows

Now, let’s create a percentage column that will make visualization easy
with donut chart.

``` r
daily_use_percent <- daily_use %>%
  group_by(usage) %>% 
  summarise(count_of_usage = n()) %>% 
  mutate(total_of_usage = sum(count_of_usage)) %>% 
  group_by(usage) %>% 
  summarise(usage_percent = count_of_usage/total_of_usage) %>% 
  mutate(labels = scales::percent(usage_percent))

daily_use_percent
```

    ## # A tibble: 3 × 3
    ##   usage        usage_percent labels
    ##   <chr>                <dbl> <chr> 
    ## 1 high use             0.5   50%   
    ## 2 low use              0.375 38%   
    ## 3 moderate use         0.125 12%

Let’s plot this using a donuts chart.

``` r
# hole size for the donut chart

h_size <- 2.5

daily_use_percent %>% 
  mutate(x = h_size) %>% 
  ggplot(mapping = aes(x = x, y = usage_percent, fill = usage)) +
  geom_col() +
  geom_text(
    aes(label = labels), position = position_stack(vjust= 0.5),
    show.legend = FALSE
    ) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "YlOrBr" ) +
  xlim(c(0.2, h_size + 0.5))+
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) +
  labs(title= "Categories of Users Based Usage Frequency")
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/usage%20categories.png?raw=true)<!-- -->

INSIGHTS

From the chart above, we can see that 50% of smart devices users, use
their devices quite frequently, which is very encouraging while 38% are
low users using their smart watches just about 9 days out of a 31 days
calendar. That presents a huge opportunity still for Bellabeat marketing
team to explore with their marketing messaging.

As you can see, this information can help Bellabeat marketing team
segment their market for more effective marketing campaigns.

### Correlation Studies

Now, we are going to be comparing some of the variables in our data to
understand if there are corelations and how this can help the Bellabeat
marketing team.

**Total Steps Vs Calories**

``` r
daily_activity_n_sleep %>% 
  ggplot(mapping = aes(x= total_steps, y = calories))+
  geom_point(color = "brown", position = "jitter")+
  geom_smooth(method = "lm", color= "orange")+
  labs(title = "Daily Steps vs Calories", x= " daily steps", y= "calories" )+
  theme(plot.title = element_text(size = 12))
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/daily%20steps%20vs%20calorie.png?raw=true)<!-- -->

**Calories Vs Sleep Record**

``` r
# We are installing beeswarm package to create a swarmplot for this relationship

install.packages("ggbeeswarm")
```

    ## Installing package into 'C:/Users/SHOW ICT/AppData/Local/R/win-library/4.3'
    ## (as 'lib' is unspecified)

    ## package 'ggbeeswarm' successfully unpacked and MD5 sums checked
    ## 
    ## The downloaded binary packages are in
    ##  C:\Users\SHOW ICT\AppData\Local\Temp\Rtmp4O06li\downloaded_packages

``` r
library(ggbeeswarm)
```

``` r
# Creation of beeswarm plot

daily_activity_n_sleep %>% 
  ggplot(aes(x= total_sleep_records, y = calories, color = total_sleep_records))+
  geom_beeswarm(cex = 2)+
  scale_color_gradient(low = "brown", high= "orange")+
  labs(title= "Calories vs Sleep Record", x = "sleep record", y= "calories")+
  theme(plot.title = element_text(size = 12))
```

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/calories%20vs%20sleep%20record.png?raw=true)<!-- -->

**Minutes Asleep vs Time in Bed**

``` r
daily_activity_n_sleep %>% 
  ggplot(aes(y= total_minutes_asleep, x = total_time_in_bed))+
  geom_point(color= "brown")+
  geom_smooth(method= "lm", se= FALSE, color = "black")+
  labs(title= "Minutes Asleep vs Time in Bed", x = "time in bed", y= "minutes asleep")+
  theme(plot.title = element_text(size = 12))
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/minutes%20asleep%20vs%20time%20in%20bed.png?raw=true)<!-- -->

### Minutes Asleep vs Calories

``` r
daily_activity_n_sleep %>% 
  ggplot(aes(x = total_minutes_asleep, y = calories))+
  geom_point(color= "brown")+
  geom_smooth(method= "lm", se= FALSE, color = "orange")+
  labs(title= "Minutes Asleep vs Calories", x = "minutes asleep", y= "calories")+
  theme(plot.title = element_text(size = 12))
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/minutes%20asleep%20vs%20calories.png?raw=true)<!-- -->

``` r
# Let's assemble all the plots in one place.

ggarrange(
  ggplot(daily_activity_n_sleep, aes(x= total_steps, y = calories))+
    geom_point(color = "brown", position = "jitter")+
    geom_smooth(method = "lm", color= "orange")+
    labs(title = "Daily Steps vs Calories", x= " daily steps", y= "calories" )+
    theme(plot.title = element_text(size = 12)),

  ggplot(daily_activity_n_sleep, aes(x = total_minutes_asleep, y = calories))+
    geom_point(color= "brown")+
    geom_smooth(method= "lm", se= FALSE, color = "orange")+
    labs(title= "Minutes Asleep vs Calories", x = "minutes asleep", y= "calories")+
    theme(plot.title = element_text(size = 12)),

  ggplot(daily_activity_n_sleep, aes(x= total_sleep_records, y = calories, color = total_sleep_records))+
    geom_beeswarm(cex = 2)+
    scale_color_gradient(low = "brown", high= "orange")+
    labs(title= "Sleep Record vs Calories", x = "sleep record", y= "calories")+
    theme(plot.title = element_text(size = 12)),

  ggplot(daily_activity_n_sleep, aes(x = total_time_in_bed, y= total_minutes_asleep))+
    geom_point(color= "brown")+
    geom_smooth(method= "lm", se= FALSE, color = "black")+
    labs(title= "Minutes Asleep vs Time in Bed", x = "time in bed", y= "minutes asleep")+
    theme(plot.title = element_text(size = 12))
)
```

    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'
    ## `geom_smooth()` using formula = 'y ~ x'

![](https://github.com/domtheanalyst/BellaBeat-Case-Study/blob/main/all%20correlation%20charts.png?raw=true)<!-- -->

### Insights

From the charts above, we begin to see some patterns.

1.  Daily Steps vs Calories

    We can see that there’s a strong positive correlation between the
    number of steps a user walks in a day and the amount of calories
    burned which is expected and why walking daily is an open secret for
    losing weight and keeping in shape.

2.  Minutes Asleep vs Calories

    We cannot see a clear correlation between minutes asleep and
    calories burned. However, we can see that there’s a slight negative
    correlation. Users who sleep less minutes, especially below 200
    minutes a day seem to burn more calories but as the quality of sleep
    increases, the data becomes mixed up, therefore we cannot say that
    the calories burned is due to sleeping less, it could be from the
    stress associated with not sleeping enough.

3.  Sleep Record vs Calories

    We can see from this chart that most of our users sleep once a day,
    and just a handful sleep twice and 3 times a day.

    There is no correlation between the number of times slept and
    calories burned, however from the chart we can see that those who
    sleep 3 times a day burn less calories that those who sleep once a
    day and twice daily.

4.  Time in Bed vs Minutes Asleep

    We can see a strong positive correlation between time in bed and
    minutes asleep. It simply means that the more time you stay in bed
    the more likely sleep you would tend to sleep.

These insights can benefit the marketing team at Bellabeat in many ways
especially in creating advertising communication that showcases the
benefits of wearing Bellabeat smartwatches.

## CONCLUSION AND RECOMMENDATION

The Bellabeat team now have an exciting basket of insights about the
users of smart devices from their daily habits to their attitude around
usage of smart devices.

We can see that there is a lot of opportunities to explore both for the
marketing and product team in using these uncovered insights to improve
the product as well the marketing campaigns at BellaBeat.
